### ISSUE TITLE
How to return response?

### ISSUE THREAD

**Issue by Arlington1985** [shawalli/flask-github-webhook#4]
Is there a way to return the response back to GitHub ?

**Comment by shawalli** [comment]
Hi, sorry for the late response! As this is just wrapper around python-github-webhook, it is bound by the contract that that library specifies. Since GitHub's webhooks come in as a POST, the library hardcodes a 204 response, which tells GitHub that the event was processed. What different response are you trying to send to GitHub?

**Comment by shawalli** [comment]
It looks like you found the issue on the core repo, but I'll link here for others.

bloomberg/python-github-webhook#18

**Comment by shawalli** [comment]
Closing this issue, as it appears to reside with the wrapped repo.
